### PR TITLE
Added 6 commands

### PR DESCRIPTION
**Pull request by BaffledJimmy**

### CODE REVIEW

**Comment by leostat** [comment]
Could you drop Just the text next time :) makes it easier!

**Comment by BaffledJimmy** [comment]
Yep sure - then dump them into a text file and push that?

**Comment by leostat** [comment]
Yaha, then I can just add a line in the 'main' updates to push it out

(Version 2 of RTFM really needs a better update process, I need to do some reading!)

**Comment by leostat** [comment]
These commands are part of 5.txt, as such closing this

**Comment by leostat** [comment]
Thanks for the commands! :)

**Pull request closed without merging**
